spring:
  application:
    name: springJDBC

  datasource:
    url: jdbc:mysql://localhost:3307/exampleDB
    username: minjiki2
    password: minjiki1234
    driver-class-name: com.mysql.cj.jdbc.Driver