spring:
  application:
    name: BoardCRUD

  datasource:
    url: jdbc:mysql://localhost:3307/boardDB
    username: minjiki2
    password: minjiki1234
    driver-class-name: com.mysql.cj.jdbc.Driver


